# Generated by Django 3.1.3 on 2020-12-01 15:02

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_crypto_fields.fields.encrypted_text_field
import django_revision.revision_field
import edc_base.model_fields.custom_fields
import edc_base.model_fields.hostname_modification_field
import edc_base.model_fields.userfield
import edc_base.model_fields.uuid_auto_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('motheo_call_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='loc_after_deliv',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, verbose_name='Location participant will be staying after delivery?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='locator_review',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Did you review this form with the participant to find out if there are any updates?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_call',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this cell number</b>?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_call_alt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this cell number</b>?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_call_tel',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this telephone number</b>?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_contact_anc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission to be contacted, through their ANC clinic?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_contact_email',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted by email</b>?'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_contact_idcc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has the participant given permission to be contacted, through their IDCC clinic?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='may_contact_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has participant given permission to be contacted at their workplace?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='next_of_kin_details',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name="Name and contact details of next of kin or any individuals participant allows us to contact if they can't be reached.(can list multiple people)"),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='loc_after_deliv',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, verbose_name='Location participant will be staying after delivery?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='locator_review',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Did you review this form with the participant to find out if there are any updates?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_call',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this cell number</b>?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_call_alt',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this cell number</b>?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_call_tel',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted on this telephone number</b>?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_contact_anc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Has the participant given permission to be contacted, through their ANC clinic?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_contact_email',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has the participant given permission <b>to be contacted by email</b>?'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_contact_idcc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has the participant given permission to be contacted, through their IDCC clinic?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='may_contact_work',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=3, verbose_name='Has participant given permission to be contacted at their workplace?, if unable to contact phone numbers'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='next_of_kin_details',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name="Name and contact details of next of kin or any individuals participant allows us to contact if they can't be reached.(can list multiple people)"),
        ),
        migrations.CreateModel(
            name='EnrollmentChecklist',
            fields=[
                ('created', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('modified', models.DateTimeField(blank=True, default=edc_base.utils.get_utcnow)),
                ('user_created', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model_fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', edc_base.model_fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', edc_base.model_fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('hiv_neg_doc', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother has documentation of negative HIV-1 status during or after pregnancy with the child who will be enrolled into Motheo')),
                ('hiv_pos_doc', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother has documentation of positive HIV-1 status during or after pregnancy with the child who will be enrolled into Motheo')),
                ('efv_art_regimen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother has documented history of treatment with EFV/TDF/3TC or EFV/TDF/FTC while pregnant with the child who will be enrolled into motheo')),
                ('dtg_art_regimen', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother has documented history of treatment with DTG/TDF/3TC or DTG/TDF/FTC while pregnant with the child who will be enrolled into motheo')),
                ('confirm_enrol', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Did you confirm that we still need to enroll women from this category (HIV status and ART status)?')),
                ('child_dob', models.DateField(verbose_name='Child date of birth')),
                ('child_age', models.IntegerField()),
                ('child_is_of_age', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Child is age 23-28 months')),
                ('child_hiv_neg', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Child is documented to have negative HIV test after 18 months of age')),
                ('child_test_date', models.DateField(verbose_name='Date of negative test')),
                ('child_test_type', models.CharField(choices=[('elisa', 'Elisa'), ('rapid_test', 'Rapid Test'), ('dna_pcr', 'DNA PCR'), ('rna_pcr', 'RNA PCR'), ('OTHER', 'Other')], max_length=15, verbose_name='Type of negative test')),
                ('child_test_type_other', edc_base.model_fields.custom_fields.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If Other, specify ...')),
                ('team_performed_test', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Test performed by Motheo study team?')),
                ('add_reasons_ineligible', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Are there any additional reason(s) why the mother-infant pair was not enrolled in this study?')),
                ('specify_reasons', models.TextField(max_length=500, verbose_name='if yes, specify: ')),
                ('consent_discussed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Study overview discussed with participant and all questions answered?')),
                ('consent_review', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Participant reviewed the informed consent and all questions answered?')),
                ('consent_signed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Participant signed the consent form?')),
                ('consent_samples', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Did the participant consent for having samples used for future research?')),
                ('consent_copy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Participant given a copy of the consent form?')),
                ('consent_received', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Consent received by study coordinator for filling or scanned?')),
                ('subject_identifier', models.CharField(max_length=360, verbose_name='Subject Identifier')),
                ('report_datetime', models.DateTimeField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.datetime_not_before_study_start, edc_base.model_validators.date.datetime_not_future])),
                ('maternal_dob', models.DateField(verbose_name='Maternal Date of birth')),
                ('maternal_age', models.IntegerField()),
                ('age_of_consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother is atleast 18 years of age')),
                ('informed_consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name="Mother is willing and able to provide written informed consent for her and her child's participation in the study")),
                ('followup_consent', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother is willing and able to follow up (with her child) for 3years')),
                ('remain_in_area', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother intends to remain in the general Gaborone area for the duration of the study')),
                ('keep_contact', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother is willing to stay in telephone contact with the study team between the 2- and 5-year visits')),
                ('nationality', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother is documented to be a Botswana citizen')),
                ('incarcerated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, verbose_name='Mother is currently involuntarily incarcerated')),
                ('site', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollment',
            },
        ),
    ]
