# Generated by Django 3.1.3 on 2020-12-02 14:27

import django.core.validators
from django.db import migrations
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ('motheo_call_manager', '0003_historicalsubjectoffstudy_subjectoffstudy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='subject_fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='subject_lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='subject_fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='subject_lname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
        migrations.AddField(
            model_name='subjectlocator',
            name='initials',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, validators=[django.core.validators.RegexValidator(message='Ensure initials consist of letters only in upper case, no spaces.', regex='^[A-Z]{2,3}$')]),
        ),
    ]
