# Generated by Django 3.1.3 on 2021-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motheo_call_manager', '0004_auto_20201202_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='anc_clinic',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name of ANC Clinic'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='anc_clinic',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Name of ANC Clinic'),
        ),
    ]
