# Generated by Django 3.1.3 on 2021-01-13 20:29

from django.db import migrations, models
import django_crypto_fields.fields.encrypted_text_field
import edc_base.model_validators.date
import edc_base.utils
import edc_protocol.validators


class Migration(migrations.Migration):

    dependencies = [
        ('motheo_call_manager', '0005_auto_20210109_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsubjectlocator',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Subject Locator'},
        ),
        migrations.AlterModelOptions(
            name='subjectlocator',
            options={'verbose_name': 'Subject Locator'},
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='next_ap_date',
            new_name='date_followup',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='email_address',
            new_name='loc_email',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='first_name',
            new_name='loc_fname',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='next_of_kin_details',
            new_name='loc_kincontact',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='last_name',
            new_name='loc_lname',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='home_village',
            new_name='loc_village',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='work_phone',
            new_name='loc_workphone',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='workplace',
            new_name='loc_workplace',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='locator_review',
            new_name='review_locator',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='next_ap_date',
            new_name='date_followup',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='email_address',
            new_name='loc_email',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='first_name',
            new_name='loc_fname',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='next_of_kin_details',
            new_name='loc_kincontact',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='last_name',
            new_name='loc_lname',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='home_village',
            new_name='loc_village',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='work_phone',
            new_name='loc_workphone',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='workplace',
            new_name='loc_workplace',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='locator_review',
            new_name='review_locator',
        ),
        migrations.RemoveField(
            model_name='historicalsubjectlocator',
            name='report_datetime',
        ),
        migrations.RemoveField(
            model_name='subjectlocator',
            name='report_datetime',
        ),
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='loc_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name='Physical address with detailed description'),
        ),
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='loc_admin',
            field=models.CharField(default='1', max_length=50, verbose_name='Administered by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsubjectlocator',
            name='loc_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.date_not_before_study_start, edc_base.model_validators.date.date_not_future], verbose_name='Date Completed'),
        ),
        migrations.AddField(
            model_name='subjectlocator',
            name='loc_address',
            field=django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text=' (Encryption: AES local)', max_length=500, null=True, verbose_name='Physical address with detailed description'),
        ),
        migrations.AddField(
            model_name='subjectlocator',
            name='loc_admin',
            field=models.CharField(default='1', max_length=50, verbose_name='Administered by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectlocator',
            name='loc_date',
            field=models.DateField(default=edc_base.utils.get_utcnow, validators=[edc_protocol.validators.date_not_before_study_start, edc_base.model_validators.date.date_not_future], verbose_name='Date Completed'),
        ),
    ]
