# Generated by Django 3.1.3 on 2021-01-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motheo_call_manager', '0006_auto_20210113_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='loc_fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='historicalsubjectlocator',
            old_name='loc_lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='loc_fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='subjectlocator',
            old_name='loc_lname',
            new_name='last_name',
        ),
    ]
