# Generated by Django 3.1.3 on 2021-01-14 08:36

from django.db import migrations
import django_crypto_fields.fields.encrypted_char_field


class Migration(migrations.Migration):

    dependencies = [
        ('motheo_call_manager', '0007_auto_20210114_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectlocator',
            name='loc_workphone',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Work Telephone'),
        ),
        migrations.AlterField(
            model_name='subjectlocator',
            name='loc_workphone',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71, null=True, verbose_name='Work Telephone'),
        ),
    ]
